### ISSUE TITLE
Won't work?

### ISSUE THREAD

**Issue by LordROR** [x753/RoR2-MP4Player#3]
I am not sure if I am not using this mod correctly, but whenever I provide either a link to a website containing an MP4, or even giving it a file location of a downloaded MP4 in chat, it does not play sound nor provide video.

**Comment by x753** [comment]
This mod requires this library to function: https://github.com/x753/RoR2-Audio-Engine-Fix/releases/tag/v1.0.0

If you aren't already, I recommend using https://thunderstore.io/package/ebkr/r2modman/ to download mods, since it'll automatically download the necessary libraries when you download a mod. 

It's also possible that you didn't restart your game after launching it once. The audio engine fix overwrites a base Risk of Rain 2 file, so the game needs to be restarted after you load it for the first time in order to use that overwritten file.
